startDelaySeconds: 0
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: 'java.lang<type=Memory><HeapMemoryUsage>(used|committed|max|init):'
    name: jvm_memory_bytes_$1
    labels:
      area: heap
    type: GAUGE

  - pattern: 'java.lang<type=Memory><NonHeapMemoryUsage>(used|committed|max|init):'
    name: jvm_memory_bytes_$1
    labels:
      area: nonheap
    type: GAUGE

  - pattern: 'java.lang<type=GarbageCollector,name=(.+)><CollectionCount>:'
    name: jvm_gc_collection_seconds_count
    labels:
      gc: "$1"
    type: COUNTER

  - pattern: 'java.lang<type=GarbageCollector,name=(.+)><CollectionTime>:'
    name: jvm_gc_collection_seconds_sum
    labels:
      gc: "$1"
    type: COUNTER
    valueFactor: 0.001

  - pattern: 'java.lang<type=Threading><ThreadCount>:'
    name: jvm_threads_live_threads
    type: GAUGE

  - pattern: 'java.lang<type=Threading><DaemonThreadCount>:'
    name: jvm_threads_daemon_threads
    type: GAUGE

  - pattern: 'java.lang<type=Threading><PeakThreadCount>:'
    name: jvm_threads_peak_threads
    type: GAUGE

  - pattern: 'java.lang<type=OperatingSystem><ProcessCpuLoad>:'
    name: process_cpu_usage
    type: GAUGE

  - pattern: 'java.lang<type=OperatingSystem><SystemCpuLoad>:'
    name: system_cpu_usage
    type: GAUGE